### ISSUE TITLE
Issue With Loading Music

### ISSUE THREAD

**Issue by ebadfd** [IamBikramPurkait/Swaralipi--Music-Player#2]
hi, some.mp3 files doe snot work on the application it shows an error. 
![2021-03-03 15_58_48-Musicolet](https://user-images.githubusercontent.com/66930150/109792344-6ab29280-7c39-11eb-99cf-666357503e5c.png)

**Comment by IamBikramPurkait** [comment]
Please can you provide me some more information about that song or can you send me that song, so I can check that on my machine.

**Comment by ebadfd** [comment]
yes sure i will. i guess there's some error with the file or something i will do a research and let you know.

**Comment by IamBikramPurkait** [comment]
okay
